name: Go CI

on:
  push:
    branches:
      - "master"
      - "feature/**"
      - "fix/**"
  pull_request:
    branches:
      - "master"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24.1'

      - name: Set up Go Workspace
        run: |
          echo "Setting up Go workspace..."
          cd go-tetris-ws
          go work sync                

      - name: Verify go.mod and go.sum
        run: |
          cd go-tetris-ws/tetris
          go mod tidy
          if ! git diff --exit-code go.mod go.sum; then
            echo "Warning: go.mod/go.sum changed. Committing changes."
            git add go.mod go.sum
            git commit -m "Fix: Auto-update go.mod and go.sum"
          fi
          
          cd ../tetris-main
          go mod tidy
          if ! git diff --exit-code go.mod go.sum; then
            echo "Warning: go.mod/go.sum changed. Committing changes."
            git add go.mod go.sum
            git commit -m "Fix: Auto-update go.mod and go.sum"
          fi

      - name: Run Linter
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest

      - name: Build Project
        run: |
          cd go-tetris-ws/tetris
          go build -v ./...

          cd ../tetris-main
          go build -v ./...